apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knurse.fullname" . }}-config
  labels:
    {{- include "knurse.labels" . | nindent 4 }}
data:
  {{ include "knurse.fullname" . }}-config.yaml: |-
    {{- tpl (toYaml .Values.app.config) . | nindent 4 }}
